kind: pipeline
type: docker
name: arm64-gcc

platform:
  arch: arm64

steps:
- name: test
  image: ubuntu
  commands:
  - apt update -y && apt install -y llvm build-essential cmake ninja-build gcc
  - mkdir build && cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - ninja
  - ninja test

---
kind: pipeline
type: docker
name: arm64-clang

platform:
  arch: arm64

steps:
- name: test
  image: ubuntu
  commands:
  - apt update -y && apt install -y llvm-8 build-essential cmake ninja-build clang-8 libc++-8-dev libc++abi-8-dev
  - mkdir build && cd build
  - env CC=clang-8 CXX=clang++-8 CXXFLAGS="-stdlib=libc++" cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - ninja
  - ninja test

---

kind: pipeline
type: docker
name: amd64

platform:
  arch: amd64

steps:
- name: test
  image: ubuntu
  commands:
  - apt update -y && apt install -y llvm build-essential cmake ninja-build
  - mkdir build && cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - ninja -j24
  - ninja test

