kind: pipeline
type: docker
name: arm64-gcc

platform:
  arch: arm64

steps:
- name: test
  image: ubuntu
  commands:
  - apt update -y && apt install -y llvm build-essential cmake ninja-build gcc
  - mkdir build && cd build
  - env CXXFLAGS="-UNDEBUG" LDFLAGS="-fuse-ld=gold" cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
  - ninja -j24
  - ctest -j24

---
kind: pipeline
type: docker
name: arm64-clang

platform:
  arch: arm64

steps:
- name: test
  image: ubuntu
  commands:
  - apt update -y && apt install -y llvm-8 build-essential cmake ninja-build clang-8 libc++-8-dev libc++abi-8-dev lld-8
  - mkdir build && cd build
  - env CC=clang-8 CXX=clang++-8 CXXFLAGS="-stdlib=libc++ -UNDEBUG" LDFLAGS="-fuse-ld=lld" cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
  - ninja
  - ctest -j24

---

kind: pipeline
type: docker
name: amd64

platform:
  arch: amd64

steps:
- name: test
  image: ubuntu
  commands:
  - apt update -y && apt install -y llvm build-essential cmake ninja-build
  - mkdir build && cd build
  - env LDFLAGS="-fuse-ld=gold" CXXFLAGS="-UNDEBUG" cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
  - ninja -j24
  - ctest -j24

